name: pass-master
services:

  ollama:
    image: ollama/ollama:latest
    profiles: ["local"]  # 'local' 프로필 지정
    container_name: passmaster-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    runtime: nvidia
    environment:
      - OLLAMA_MAX_LOADED_MODELS=1
      # - OLLAMA_KEEP_ALIVE=1m
      - NVIDIA_VISIBLE_DEVICES=all
    # 💡 entrypoint 추가: 서버 실행 -> 잠시 대기(서버 부팅 시간) -> 모델 풀 -> 프로세스 유지
    # 💡 llama3 모델
    # entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 10 && ollama pull llama3 && wait"]
    # 💡 exaone3.5 모델
    # entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 10 && ollama pull exaone3.5:7.8b && wait"]
    # 💡 gemma4 모델
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 10 && ollama pull gemma4:e4b && wait"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  neo4j:
    image: neo4j:5.18
    container_name: passmaster-neo4j
    hostname: passmaster-neo4j
    ports:
      - "7474:7474"   # 브라우저 UI
      - "7687:7687"   # Bolt (앱 연결)
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      # - NEO4J_dbms_memory_heap_initial_size=512m
      # - NEO4J_dbms_memory_heap_max_size=1G
      - NEO4J_server_memory_pagecache_size=1G
    restart: unless-stopped

  tei:
    image: ghcr.io/huggingface/text-embeddings-inference:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    container_name: passmaster-tei
    ports:
      - "8080:80"
    volumes:
      - tei_data:/data
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: ["--model-id", "BAAI/bge-m3", "--port", "80"]
    # command: ["--model-id", "intfloat/multilingual-e5-small", "--port", "80"]
    # shm_size: '2gb' # GPU 가속 시 공유 메모리 확장이 안정성에 도움됨
    restart: unless-stopped

  tei-reranker:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
    profiles: ["local"]  # 'local' 프로필 지정
    container_name: passmaster-tei-reranker
    ports:
      - "8081:80"
    volumes:
      - tei_reranker_data:/data
    command: ["--model-id", "BAAI/bge-reranker-base", "--port", "80"]
    # command: ["--model-id", "BAAI/bge-reranker-v2-m3", "--port", "80"]
    restart: unless-stopped

volumes:
  ollama_data:
  neo4j_data:
  tei_data:
  tei_reranker_data:
